apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2024-10-15T14:59:22Z"
  generation: 1
  labels:
    operators.coreos.com/apicurio-registry.openshift-operators: ""
  name: apicurio-registry
  namespace: openshift-operators
  resourceVersion: "34999"
  uid: 02ce170a-0ee2-4931-839b-6020dfc093d3
spec:
  channel: 2.x
  installPlanApproval: Automatic
  name: apicurio-registry
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: apicurio-registry-operator.v1.1.3-v2.6.4.final
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: certified-operators
      namespace: openshift-marketplace
      resourceVersion: "32029"
      uid: 00bc1d14-0148-44b8-b96d-dccd119132f1
    healthy: true
    lastUpdated: "2024-10-15T14:59:37Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: community-operators
      namespace: openshift-marketplace
      resourceVersion: "34318"
      uid: 4bc526fb-6dd9-4e31-91ab-94484bd1deb6
    healthy: true
    lastUpdated: "2024-10-15T14:59:37Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-marketplace
      namespace: openshift-marketplace
      resourceVersion: "34278"
      uid: 1cce6cb5-7d2d-4a6c-95bf-8ccc0f0749ad
    healthy: true
    lastUpdated: "2024-10-15T14:59:37Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-operators
      namespace: openshift-marketplace
      resourceVersion: "33897"
      uid: f2566ecb-87fb-4441-af05-bea716c3e54a
    healthy: true
    lastUpdated: "2024-10-15T14:59:37Z"
  conditions:
  - lastTransitionTime: "2024-10-15T14:59:39Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  currentCSV: apicurio-registry-operator.v1.1.3-v2.6.4.final
  installPlanGeneration: 2
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-2tp6n
    namespace: openshift-operators
    resourceVersion: "34835"
    uid: ea130a92-fc77-46aa-a918-2e3e99a3d436
  installedCSV: apicurio-registry-operator.v1.1.3-v2.6.4.final
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-2tp6n
    uuid: ea130a92-fc77-46aa-a918-2e3e99a3d436
  lastUpdated: "2024-10-15T14:59:50Z"
  state: AtLatestKnown
