name: build-and-push-image

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/acme/**'
      - 'src/main/docker/Dockerfile.jvm'
      - 'pom.xml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          ./mvnw package -DskipTests \
          -Dquarkus.container-image.builder=docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_NAME=ghcr.io/ansaha/quarkus-ping-test:latest
          docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME .
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_NAME