name: build-image

on:
  pull-request:
    branches:
      - main
    paths:
      - 'src/main/java/org/acme/**'

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/ansahaRH-Lilly/quarkus-ping-test:latest
          docker push ghcr.io/ansahaRH-Lilly/quarkus-ping-test:latest