name: build-and-push-image

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/acme/**'
      - 'src/main/docker/Dockerfile.jvm'
      - 'pom.xml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/ansaharh-lilly/quarkus-ping-test:latest .
          docker push ghcr.io/ansaharh-lilly/quarkus-ping-test:latest