name: build-image

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/acme/**'
      - 'Dockerfile'  # Add this line to trigger on Dockerfile changes

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Inventory Image
        run: |
          if [ -f Dockerfile ]; then
            echo "Using Dockerfile in root directory"
            docker build . --tag ghcr.io/ansaharh-lilly/quarkus-ping-test:latest
          elif [ -f src/main/docker/Dockerfile.jvm ]; then
            echo "Using Dockerfile.jvm in src/main/docker directory"
            docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/ansaharh-lilly/quarkus-ping-test:latest .
          else
            echo "Error: No Dockerfile found"
            exit 1
          fi
          docker push ghcr.io/ansaharh-lilly/quarkus-ping-test:latest